/**
 * @type {Array<{type: 'light' | 'medium' | 'heavy' | 'special' | 'mortar', name: string, penetration: number | null, reloadTimeSeconds: number, range: number | null, maxAngleDeg: number | null, scatter: number | null}>}
 * @description Cannons data
 * @property {string} type - Cannon type (light, medium, heavy, special, mortar)
 * @property {string} name - Cannon name
 * @property {number | null} penetration - Cannon penetration
 * @property {number} reloadTimeSeconds - Cannon reload time in seconds
 * @property {number | null} range - Cannon range (for mortars, this is a range string like "60-135")
 * @property {number | null} maxAngleDeg - Cannon max angle in degrees
 * @property {number | null} scatter - Cannon scatter
 */
export const cannons = [
  {
    type: "light",
    name: "6-фн. Ржавая пушка",
    penetration: 13,
    reloadTimeSeconds: 10.5,
    range: 125,
    maxAngleDeg: 34,
    scatter: 8.5,
  },
  {
    type: "light",
    name: "8-фн. Пушка",
    penetration: 14,
    reloadTimeSeconds: 9,
    range: 130,
    maxAngleDeg: 31,
    scatter: 9.5,
  },
  {
    type: "light",
    name: "6-фн. Кулеврина",
    penetration: 14,
    reloadTimeSeconds: 15.5,
    range: 135,
    maxAngleDeg: 17,
    scatter: 5,
  },
  {
    type: "light",
    name: "8-фн. Кулеврина",
    penetration: 15,
    reloadTimeSeconds: 13,
    range: 140,
    maxAngleDeg: 16,
    scatter: 6,
  },
  {
    type: "light",
    name: "12-фн. Карронада",
    penetration: 20,
    reloadTimeSeconds: 22,
    range: 105,
    maxAngleDeg: 26,
    scatter: 9.5,
  },
  {
    type: "light",
    name: "16-фн. Карронада",
    penetration: 21.5,
    reloadTimeSeconds: 19.5,
    range: 110,
    maxAngleDeg: 23,
    scatter: 11.5,
  },
  // Medium cannons (for ships IV-I rank)
  {
    type: "medium",
    name: "16-фн. Пушка",
    penetration: 15,
    reloadTimeSeconds: 12,
    range: 130,
    maxAngleDeg: 29,
    scatter: 10.5,
  },
  {
    type: "medium",
    name: "18-фн. Пушка",
    penetration: 16,
    reloadTimeSeconds: 10.5,
    range: 135,
    maxAngleDeg: 26,
    scatter: 12,
  },
  {
    type: "medium",
    name: "20-фн. Адмиральская",
    penetration: 17,
    reloadTimeSeconds: 13.5,
    range: 130,
    maxAngleDeg: 21,
    scatter: 11,
  },
  {
    type: "medium",
    name: "24-фн. Пушка",
    penetration: 17,
    reloadTimeSeconds: 12,
    range: 140,
    maxAngleDeg: 29,
    scatter: 8.5,
  },
  {
    type: "medium",
    name: "16-фн. Кулеврина",
    penetration: 15,
    reloadTimeSeconds: 17.5,
    range: 140,
    maxAngleDeg: 14,
    scatter: 6,
  },
  {
    type: "medium",
    name: "18-фн. Кулеврина",
    penetration: 16,
    reloadTimeSeconds: 14,
    range: 145,
    maxAngleDeg: 15,
    scatter: 5.5,
  },
  {
    type: "medium",
    name: "24-фн. Кулеврина",
    penetration: 17,
    reloadTimeSeconds: 15,
    range: 150,
    maxAngleDeg: 14,
    scatter: 5,
  },
  {
    type: "medium",
    name: "24-фн. Карронада",
    penetration: 22,
    reloadTimeSeconds: 24,
    range: 110,
    maxAngleDeg: 25,
    scatter: 9,
  },
  {
    type: "medium",
    name: "32-фн. Карронада",
    penetration: 24,
    reloadTimeSeconds: 26,
    range: 115,
    maxAngleDeg: 24,
    scatter: 8.5,
  },
  {
    type: "medium",
    name: "32-фн. Пушка",
    penetration: 18,
    reloadTimeSeconds: 12,
    range: 140,
    maxAngleDeg: 20,
    scatter: 10,
  },
  {
    type: "medium",
    name: "6-фн. Сдвоенная",
    penetration: 16,
    reloadTimeSeconds: 20,
    range: 115,
    maxAngleDeg: 12,
    scatter: 8,
  },
  {
    type: "medium",
    name: "8-фн. Сдвоенная",
    penetration: 17,
    reloadTimeSeconds: 18,
    range: 120,
    maxAngleDeg: 11,
    scatter: 7.5,
  },
  {
    type: "medium",
    name: "10-фн. Строенная",
    penetration: 18,
    reloadTimeSeconds: 22,
    range: 125,
    maxAngleDeg: 10,
    scatter: 7,
  },
  {
    type: "medium",
    name: "Василиск",
    penetration: 68,
    reloadTimeSeconds: 18.5,
    range: 150,
    maxAngleDeg: 25,
    scatter: 6,
  },
  {
    type: "medium",
    name: "Зевс",
    penetration: 72,
    reloadTimeSeconds: 21.5,
    range: 155,
    maxAngleDeg: 21,
    scatter: 5.5,
  },
  {
    type: "medium",
    name: "Онагр",
    penetration: 90,
    reloadTimeSeconds: 24,
    range: 160,
    maxAngleDeg: 18,
    scatter: 5,
  },
  // Heavy cannons (for ships II-I rank)
  {
    type: "heavy",
    name: "32-фн. Пушка",
    penetration: 18,
    reloadTimeSeconds: 13,
    range: 145,
    maxAngleDeg: 28,
    scatter: 8,
  },
  {
    type: "heavy",
    name: "32-фн. Инрог",
    penetration: 19,
    reloadTimeSeconds: 14,
    range: 150,
    maxAngleDeg: 27,
    scatter: 7.5,
  },
  {
    type: "heavy",
    name: "32-фн. Длинная пушка",
    penetration: 18,
    reloadTimeSeconds: 16,
    range: 155,
    maxAngleDeg: 13,
    scatter: 4.5,
  },
  {
    type: "heavy",
    name: "38-фн. Иерихон",
    penetration: 20,
    reloadTimeSeconds: 15,
    range: 155,
    maxAngleDeg: 26,
    scatter: 7,
  },
  {
    type: "heavy",
    name: "42-фн. Пушка",
    penetration: 19,
    reloadTimeSeconds: 14,
    range: 150,
    maxAngleDeg: 27,
    scatter: 7.5,
  },
  {
    type: "heavy",
    name: "42-фн. Карронада",
    penetration: 26,
    reloadTimeSeconds: 28,
    range: 120,
    maxAngleDeg: 23,
    scatter: 8,
  },
  {
    type: "heavy",
    name: "48-фн. Исполин",
    penetration: 28,
    reloadTimeSeconds: 30,
    range: 125,
    maxAngleDeg: 22,
    scatter: 7.5,
  },
  {
    type: "heavy",
    name: "20-фн. Сдвоенная",
    penetration: 19,
    reloadTimeSeconds: 19,
    range: 125,
    maxAngleDeg: 11,
    scatter: 7,
  },
  {
    type: "heavy",
    name: "16-фн. Строенная",
    penetration: 20,
    reloadTimeSeconds: 21,
    range: 130,
    maxAngleDeg: 9,
    scatter: 6.5,
  },
  {
    type: "heavy",
    name: "Гильгамеш",
    penetration: 96,
    reloadTimeSeconds: 25,
    range: 160,
    maxAngleDeg: 16,
    scatter: 4.5,
  },
  {
    type: "heavy",
    name: "Мьельнир",
    penetration: 120,
    reloadTimeSeconds: 28,
    range: 165,
    maxAngleDeg: 14,
    scatter: 4,
  },
  // Special cannons
  {
    type: "special",
    name: "Алхимический огонь",
    penetration: null, // Special: 80/sec damage
    reloadTimeSeconds: 468,
    range: 60,
    maxAngleDeg: 6,
    scatter: 10,
  },
  {
    type: "special",
    name: "Имперская бомбарда",
    penetration: 34,
    reloadTimeSeconds: 22,
    range: 135,
    maxAngleDeg: 6,
    scatter: 12,
  },
  // Mortars
  {
    type: "mortar",
    name: "Мортира 6-дюйм.",
    penetration: 100,
    reloadTimeSeconds: 20,
    range: null, // Range: 60-135
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Мортира 7-дюйм.",
    penetration: 125,
    reloadTimeSeconds: 24,
    range: null, // Range: 75-145
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Мортира 8-дюйм.",
    penetration: 150,
    reloadTimeSeconds: 31,
    range: null, // Range: 85-155
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Мортира 9-дюйм.",
    penetration: 175,
    reloadTimeSeconds: 38,
    range: null, // Range: 95-165
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Тяжелая мортира",
    penetration: 200,
    reloadTimeSeconds: 45,
    range: null, // Range: 105-175
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Мортира 10-дюйм.",
    penetration: 225,
    reloadTimeSeconds: 52,
    range: null, // Range: 115-185
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Мортира 11-дюйм.",
    penetration: 250,
    reloadTimeSeconds: 59,
    range: null, // Range: 125-195
    maxAngleDeg: null,
    scatter: null,
  },
  {
    type: "mortar",
    name: "Метатель бочек",
    penetration: 300,
    reloadTimeSeconds: 66,
    range: null, // Range: 135-205
    maxAngleDeg: null,
    scatter: null,
  },
];
