/**
 * @type {Array<{type: 'light' | 'medium' | 'heavy' | 'special' | 'mortar', isBombard: boolean, name: string, penetration: number | null, reloadTimeSeconds: number, range: number | null, maxAngleDeg: number | null, scatter: number | null, shotsPerLoad: number}>}
 * @description Cannons data
 * @property {string} type - Cannon type (light, medium, heavy, special, mortar)
 * @property {boolean} isBombard - If cannon can only be installed on nose/butt
 * @property {string} name - Cannon name
 * @property {number | null} penetration - Cannon penetration
 * @property {number} reloadTimeSeconds - Cannon reload time in seconds
 * @property {number | null} range - Cannon range (for mortars, this is a range string like "60-135")
 * @property {number | null} maxAngleDeg - Cannon max angle in degrees
 * @property {number | null} scatter - Cannon scatter
 * @property {number} shotsPerLoad - Number of shots per load
 */
export const cannons = [
  {
    type: "light",
    isBombard: false,
    name: "6-фн. Ржавая пушка",
    penetration: 13,
    reloadTimeSeconds: 10.5,
    range: 125,
    maxAngleDeg: 34,
    scatter: 8.5,
    shotsPerLoad: 1,
  },
  {
    type: "light",
    isBombard: false,
    name: "8-фн. Пушка",
    penetration: 14,
    reloadTimeSeconds: 9,
    range: 130,
    maxAngleDeg: 31,
    scatter: 9.5,
    shotsPerLoad: 1,
  },
  {
    type: "light",
    isBombard: false,
    name: "6-фн. Кулеврина",
    penetration: 14,
    reloadTimeSeconds: 15.5,
    range: 135,
    maxAngleDeg: 17,
    scatter: 5,
    shotsPerLoad: 1,
  },
  {
    type: "light",
    isBombard: false,
    name: "8-фн. Кулеврина",
    penetration: 15,
    reloadTimeSeconds: 13,
    range: 140,
    maxAngleDeg: 16,
    scatter: 6,
    shotsPerLoad: 1,
  },
  {
    type: "light",
    isBombard: false,
    name: "12-фн. Карронада",
    penetration: 20,
    reloadTimeSeconds: 22,
    range: 105,
    maxAngleDeg: 26,
    scatter: 9.5,
    shotsPerLoad: 1,
  },
  {
    type: "light",
    isBombard: false,
    name: "16-фн. Карронада",
    penetration: 21.5,
    reloadTimeSeconds: 19.5,
    range: 110,
    maxAngleDeg: 23,
    scatter: 11.5,
    shotsPerLoad: 1,
  },
  // Medium cannons (for ships IV-I rank)
  {
    type: "medium",
    isBombard: false,
    name: "16-фн. Пушка",
    penetration: 14,
    reloadTimeSeconds: 12,
    range: 130,
    maxAngleDeg: 29,
    scatter: 10.5,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "18-фн. Пушка",
    penetration: 15,
    reloadTimeSeconds: 10.5,
    range: 135,
    maxAngleDeg: 26,
    scatter: 12,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "20-фн. Адмиральская",
    penetration: 17,
    reloadTimeSeconds: 13.5,
    range: 130,
    maxAngleDeg: 21,
    scatter: 11,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "16-фн. Кулеврина",
    penetration: 15,
    reloadTimeSeconds: 17.5,
    range: 140,
    maxAngleDeg: 14,
    scatter: 6,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "18-фн. Длинная пушка",
    penetration: 16,
    reloadTimeSeconds: 15,
    range: 145,
    maxAngleDeg: 13,
    scatter: 8,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "22-фн. Испепеляющая",
    penetration: 19,
    reloadTimeSeconds: 26,
    range: 148,
    maxAngleDeg: 9,
    scatter: 9.5,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "24-фн. Карронада",
    penetration: 21.5,
    reloadTimeSeconds: 25.5,
    range: 110,
    maxAngleDeg: 21,
    scatter: 12,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "28-фн. Карронада",
    penetration: 23,
    reloadTimeSeconds: 22.5,
    range: 115,
    maxAngleDeg: 20,
    scatter: 14.5,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: false,
    name: "32-фн. Буревестник",
    penetration: 25.5,
    reloadTimeSeconds: 27.5,
    range: 105,
    maxAngleDeg: 16,
    scatter: 13,
    shotsPerLoad: 1,
  },
  // Heavy cannons (for ships II-I rank)
  {
    type: "heavy",
    isBombard: false,
    name: "32-фн. Пушка",
    penetration: 17.5,
    reloadTimeSeconds: 12,
    range: 140,
    maxAngleDeg: 20,
    scatter: 15,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: false,
    name: "32-фн. Инрог",
    penetration: 20,
    reloadTimeSeconds: 16,
    range: 135,
    maxAngleDeg: 16,
    scatter: 13.5,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: false,
    name: "32-фн. Длинная пушка",
    penetration: 18.5,
    reloadTimeSeconds: 22,
    range: 150,
    maxAngleDeg: 10,
    scatter: 10,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: false,
    name: "38-фн. Иерихон",
    penetration: 22,
    reloadTimeSeconds: 30.5,
    range: 153,
    maxAngleDeg: 7,
    scatter: 12,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: false,
    name: "42-фн. Карронада",
    penetration: 27,
    reloadTimeSeconds: 26,
    range: 120,
    maxAngleDeg: 15,
    scatter: 18,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: false,
    name: "48-фн. Исполин",
    penetration: 30,
    reloadTimeSeconds: 32,
    range: 110,
    maxAngleDeg: 12,
    scatter: 16,
    shotsPerLoad: 1,
  },
  // Bombards
  //   Lite bombards
  {
    type: "light",
    isBombard: true,
    name: "Василиск",
    penetration: 17.5,
    reloadTimeSeconds: 18.5,
    range: 150,
    maxAngleDeg: 25,
    scatter: 4,
    shotsPerLoad: 1,
  },
  {
    type: "light",
    isBombard: true,
    name: "6 фн. Сдвоенная",
    penetration: 16,
    reloadTimeSeconds: 20,
    range: 115,
    maxAngleDeg: 12,
    scatter: 9,
    shotsPerLoad: 2,
  },
  {
    type: "light",
    isBombard: true,
    name: "Посейдон",
    penetration: 26,
    reloadTimeSeconds: 18,
    range: 80,
    maxAngleDeg: 30,
    scatter: 11,
    shotsPerLoad: 1,
  },
  //   Medium bombards
  {
    type: "medium",
    isBombard: true,
    name: "Зевс",
    penetration: 19,
    reloadTimeSeconds: 21.5,
    range: 155,
    maxAngleDeg: 21,
    scatter: 5,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: true,
    name: "14-фн. Сдвоенная",
    penetration: 17,
    reloadTimeSeconds: 23.5,
    range: 120,
    maxAngleDeg: 10,
    scatter: 11,
    shotsPerLoad: 2,
  },
  {
    type: "medium",
    isBombard: true,
    name: "Онагр",
    penetration: 28,
    reloadTimeSeconds: 20.5,
    range: 85,
    maxAngleDeg: 25,
    scatter: 13.5,
    shotsPerLoad: 1,
  },
  {
    type: "medium",
    isBombard: true,
    name: "10-фн. Строенная",
    penetration: 14,
    reloadTimeSeconds: 28.5,
    range: 135,
    maxAngleDeg: 8,
    scatter: 13,
    shotsPerLoad: 3,
  },
  //   Heavy bombards
  {
    type: "heavy",
    isBombard: true,
    name: "Гильгамеш",
    penetration: 22,
    reloadTimeSeconds: 25,
    range: 160,
    maxAngleDeg: 16,
    scatter: 6,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: true,
    name: "20-фн. Сдвоенная",
    penetration: 20,
    reloadTimeSeconds: 27,
    range: 125,
    maxAngleDeg: 8,
    scatter: 14,
    shotsPerLoad: 2,
  },
  {
    type: "heavy",
    isBombard: true,
    name: "Мьельнир",
    penetration: 32.5,
    reloadTimeSeconds: 24,
    range: 90,
    maxAngleDeg: 20,
    scatter: 17,
    shotsPerLoad: 1,
  },
  {
    type: "heavy",
    isBombard: true,
    name: "16-фн. Строенная",
    penetration: 16.5,
    reloadTimeSeconds: 33,
    range: 140,
    maxAngleDeg: 6,
    scatter: 16,
    shotsPerLoad: 3,
  },
  // // Special cannons
  // {
  //   type: "special",
  //   name: "Алхимический огонь",
  //   penetration: null, // Special: 80/sec damage
  //   reloadTimeSeconds: 468,
  //   range: 60,
  //   maxAngleDeg: 6,
  //   scatter: 10,
  // },
  // {
  //   type: "special",
  //   name: "Имперская бомбарда",
  //   penetration: 34,
  //   reloadTimeSeconds: 22,
  //   range: 135,
  //   maxAngleDeg: 6,
  //   scatter: 12,
  // },
  // // Mortars
  // {
  //   type: "mortar",
  //   name: "Мортира 6-дюйм.",
  //   penetration: 100,
  //   reloadTimeSeconds: 20,
  //   range: null, // Range: 60-135
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Мортира 7-дюйм.",
  //   penetration: 125,
  //   reloadTimeSeconds: 24,
  //   range: null, // Range: 75-145
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Мортира 8-дюйм.",
  //   penetration: 150,
  //   reloadTimeSeconds: 31,
  //   range: null, // Range: 85-155
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Мортира 9-дюйм.",
  //   penetration: 175,
  //   reloadTimeSeconds: 38,
  //   range: null, // Range: 95-165
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Тяжелая мортира",
  //   penetration: 200,
  //   reloadTimeSeconds: 45,
  //   range: null, // Range: 105-175
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Мортира 10-дюйм.",
  //   penetration: 225,
  //   reloadTimeSeconds: 52,
  //   range: null, // Range: 115-185
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Мортира 11-дюйм.",
  //   penetration: 250,
  //   reloadTimeSeconds: 59,
  //   range: null, // Range: 125-195
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
  // {
  //   type: "mortar",
  //   name: "Метатель бочек",
  //   penetration: 300,
  //   reloadTimeSeconds: 66,
  //   range: null, // Range: 135-205
  //   maxAngleDeg: null,
  //   scatter: null,
  // },
];
